poam/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^upload_poam/(?P<pk>[0-9]+)/$', views.UploadPOAMView.as_view(), name='upload-poam'),
    url(r'^edit_system/(?P<pk>[0-9]+)/$', views.EditSystemView.as_view(), name='edit-system'),
    url(r'^upload_artifact/(?P<pk>[0-9]+)/$', views.UploadArtifactView.as_view(), name='upload-artifact'),
    url(r'^upload_device/(?P<pk>[0-9]+)/$', views.UploadDeviceView.as_view(), name='upload-device'),
    url(r'^export_poam/(?P<pk>[0-9]+)/$', views.ExportPoamView.as_view(), name='export-poam'),
    url(r'^export_hw_sw_list/(?P<pk>[0-9]+)/$', views.ExportHwSwView.as_view(), name='export-hw-sw-list'),
    url(r'^edit_devices/(?P<pk>[0-9]+)/$', views.SelectDeviceView.as_view(), name='select-device'),
    url(r'^edit_device/(?P<pk>[0-9]+)/$', views.EditDeviceView.as_view(), name='edit-device'),
    url(r'^select_system/$', views.SelectSystemView.as_view(), name='select-system'),
    url(r'^add_device/(?P<pk>[0-9]+)/$', views.AddDeviceView.as_view(), name='add-device'),
    url(r'^new_system/$', views.NewSystemView.as_view(), name='new-system'),
    url(r'^new_poc/$', views.NewPOCView.as_view(), name='new-poc'),
]

webanator/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^poam/', include('poam.urls', namespace='poam')),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
]

poam/forms.py
from django import forms
from .models import *


# Create the form class.
class SystemForm(forms.ModelForm):

    class Meta:
        model = System
        exclude = ['update_date', 'create_date']


class NewPOCForm(forms.ModelForm):

    class Meta:
        model = PointOfContact
        fields = "__all__"


class WeaknessModelForm(forms.ModelForm):

    class Meta:
        model = Weakness
        exclude = "__all__"


class DeviceForm(forms.ModelForm):

    class Meta:
        model = Device
        fields = ['name', 'type', 'hardware']


# class DeviceWeaknessForm(ModelForm):
#
# 	class Meta:
# 		model = DeviceWeakness
# 		fields = "__all__"


class DocumentForm(forms.Form, forms.ModelForm):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    FILE_TYPE_CHOICES = [
        ('stig_checklist_file','STIG Checklist File'),
        ('nessus_scan_file', 'Nessus Scan File'),
        ('rmf_control_review_file', 'RMF Control Review File'),
        # ('cci_list', 'Update to CCI List')
    ]
    file_type = forms.CharField(label='File Type', widget=forms.RadioSelect(choices=FILE_TYPE_CHOICES))

    class Meta:
        model = Weakness
        fields = ['system', 'point_of_contact', 'source_identifying_event', 'source_identifying_tool', 'source_identifying_date', 'devices']

        widgets = {
            'source_identifying_date': forms.DateInput(attrs={'type': 'date'}, format=('%Y-%m-%d'))
        }

    def __init__(self, system, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        self.fields['system'].required = True
        self.fields['system'].initial = system
        self.fields['devices'].queryset = Device.objects.filter(system=system).order_by('name')
        self.fields['devices'].required = False


class POAMForm(forms.ModelForm):
    file = forms.FileField()

    class Meta:
        model = System
        fields = ['name', 'file']

        widgets = {
            'name': forms.HiddenInput()
        }


class DeviceUploadForm(forms.ModelForm):
    file = forms.FileField()

    class Meta:
        model = System
        fields = ['file',]

poam/views.py
from django.shortcuts import render, redirect, reverse
from django.views import generic
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from xml.etree import ElementTree
from django.db import IntegrityError

import openpyxl
import datetime
# import os

from .forms import *
from .models import *


# Create your views here.
class UploadArtifactView(LoginRequiredMixin, generic.CreateView):
    template_name = 'poam/upload_artifact.html'
    model = Weakness
    form_class = DocumentForm

    def get(self, request, *args, **kwargs):
        system = System.objects.get(id=self.kwargs['pk'])
        form = self.form_class(initial=self.initial, system=system)
        return render(request, self.template_name, {'form': form, 'system': system})

    def get_form_kwargs(self):
        kwargs = super(UploadArtifactView, self).get_form_kwargs()
        kwargs['system'] = System.objects.get(id=self.kwargs['pk'])
        return kwargs

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('file')
        if form.is_valid():
            form.cleaned_data['file'] = []
            for f in files:
                form.cleaned_data['file'].append(f)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        source_id = form.cleaned_data['source_identifying_event']
        source_tool = form.cleaned_data['source_identifying_tool']
        source_date = form.cleaned_data['source_identifying_date']
        system = System.objects.get(id=self.kwargs['pk'])
        poc = form.cleaned_data['point_of_contact']
        file_type = form.cleaned_data['file_type']
        device_queryset = form.cleaned_data['devices']
        for data in form.cleaned_data['file']:
            # read and parse the file, create a Python dictionary `data_dict` from it
            # start loop here for each Vuln_num in xml upload get Rule_title, Vuln_discuss,
            # Comments, IA_Controls, Check_Content, Severity, Stigid
            # Need check and message to make sure Trey or more than likely Zac doesn't do something dumb
            if file_type == 'stig_checklist_file':
                tree = ElementTree.parse(data)
                root = tree.getroot()
                if root.tag == "CHECKLIST":
                    for vuln in root.findall('.//VULN'):
                        status = vuln.find('STATUS').text
                        comments = vuln.find('COMMENTS').text
                        finding_details = vuln.find('FINDING_DETAILS').text
                        severity = vuln[1][1].text
                        title = vuln[5][1].text
                        description = vuln[6][1].text
                        chk_content = vuln[8][1].text
                        fix_text = vuln[9][1].text
                        stig_ref = vuln[22][1].text
                        vuln_id = vuln[0][1].text
                        diacap_ia_control = None
                        try:
                            vuln_id = VulnId(vuln_id=vuln_id)
                            vuln_id.save()
                        except IntegrityError:
                            vuln_id = VulnId.objects.get(vuln_id=vuln_id.vuln_id)
                        try:
                            cci = vuln[24][1].text
                            cci = CCI.objects.get(cci=cci)
                        except:
                            diacap_ia_control = vuln[7][1].text
                            cci = None
                        if status == 'Open':
                            for device in device_queryset:
                                if not Device.objects.filter(system=system, name=device).exists():
                                    messages.error(self.request, 'Woops! One of the devices is not in the database')
                                else:
                                    device = Device.objects.get(system=system, name=device)
                                    if Weakness.objects.filter(devices__id=device.id, vuln_id=vuln_id.id).exists():
                                        Weakness.objects.filter(system=system, vuln_id=vuln_id.id).update(comments=comments, finding_details=finding_details,
                                        stig_ref=stig_ref, raw_severity=severity, source_identifying_event=source_id,
                                        source_identifying_tool=source_tool, check_contents=chk_content, fix_text=fix_text,
                                        point_of_contact=PointOfContact.objects.get(name=poc).id, status=status, security_control=diacap_ia_control)
                                        if cci is not None:
                                            Weakness.objects.filter(system=system, vuln_id=vuln_id.id).update(cci=cci.id)
                                    else:
                                        data_dict = {'title': title, 'description': description, 'status': status,
                                                     'comments': comments, 'finding_details': finding_details, 'stig_ref': stig_ref,'raw_severity': severity,
                                                     'source_identifying_event': source_id, 'source_identifying_tool': source_tool, 'source_identifying_date': source_date,
                                                     'vuln_id': vuln_id.id, 'check_contents': chk_content, 'fix_text': fix_text, 'system': system.id,
                                                     'point_of_contact': poc.id, 'devices': device_queryset, 'security_control': diacap_ia_control}
                                        if cci is not None:
                                            data_dict['cci'] = cci.id
                                        form = WeaknessModelForm(data_dict)
                                        try:
                                            form.save()
                                        except:
                                            messages.error(self.request, '{} had error when saving to database. {}'.format(vuln_id, form.errors))
                        else:
                            continue
                else:
                    messages.error(self.request, 'Wrong File Type, Zac!')
                    return redirect(reverse("poam:upload-artifact"))
            elif file_type == 'rmf_control_review_file':
                try:
                    wb = openpyxl.load_workbook(data)
                    sheet = wb.active
                except:
                    messages.error(self.request, 'Wrong File Type, Zac!')
                    return redirect(reverse("poam:upload-artifact"))
                else:
                    for row in range(2, sheet.max_row + 1):
                        title = sheet['B{}'.format(row)].value
                        status = sheet['C{}'.format(row)].value
                        comments = sheet['D{}'.format(row)].value
                        control_number = sheet['A{}'.format(row)].value
                        for device in device_queryset:
                            if not Device.objects.filter(system=system, name=device).exists():
                                messages.error(self.request, 'Woops! One of the devices is not in the database')
                            else:
                                device = Device.objects.get(system=system, name=device)
                            if control_number is not None:
                                try:
                                    security_control = SecurityControl(title=title, control_number=control_number, description='')
                                    security_control.save()
                                except IntegrityError:
                                    security_control = SecurityControl.objects.get(control_number=control_number)
                                    print(security_control.control_number)
                                try:
                                    vuln_id = VulnId(vuln_id=security_control.control_number)
                                    vuln_id.save()
                                except IntegrityError:
                                    vuln_id = VulnId.objects.get(vuln_id=security_control.control_number)

                                if Weakness.objects.filter(title=security_control.title, devices=device.id).exists():
                                    print('hi')
                                    print(vuln_id.vuln_id)
                                    Weakness.objects.filter(title=security_control.title, devices=device.id).update(status=status, comments=comments, source_identifying_event=source_id, source_identifying_tool=source_tool, security_control=security_control.control_number, source_identifying_date=source_date, system=System.objects.get(name=system).id, point_of_contact=PointOfContact.objects.get(name=poc).id, vuln_id=vuln_id)
                                else:
                                    continue
                                    # if status == 'Planned':
                                    #     data_dict = {'title': title, 'description': '', 'status': status, 'comments': comments, 'source_identifying_event': source_id, 'source_identifying_tool': source_tool, 'devices': device_queryset, 'security_control': security_control, 'source_identifying_date' : source_date, 'system': System.objects.get(name=system).id, 'point_of_contact': PointOfContact.objects.get(name=poc).id, 'vuln_id' : security_control}
                                    #     form = WeaknessModelForm(data_dict)
                                    #     try:
                                    #         form.save()
                                    #     except:

poam/templates/poam/add-device.html
{% extends "base.html" %}

{% block title %}New Device{% endblock %}

{% block content %}
    <h1>New Device</h1>

    <h3>System: {{ system.name }}</h3>
    <form class="" action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" name="button">Submit</button>
    </form><br>
    <a href="{% url 'poam:edit-system' system.id %}">Edit System</a>

{% endblock %}

poam/templates/poam/edit-device.html
{% extends 'base.html' %}

{% block title %}Edit Device {% endblock title %}

{% block content %}
    <h1>Edit {{ device.name }} Device</h1>
    <div class="">
        <form class="" action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save</button>
        </form><br>
    </div>
{% endblock content %}

poam/templates/poam/edit-system.html
{% extends 'base.html' %}

{% block title %}Edit System{% endblock %}

{% block content %}
    <h1>Edit {{ system.name }} System</h1>

    <form class="" action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
    <br>or<br><br>

    <a href="{% url 'poam:upload-artifact' system.id %}">Upload Artifacts</a><br>
    <a href="{% url 'poam:upload-poam' system.id %}">Upload POA&M</a><br>
    <a href="{% url 'poam:upload-device' system.id %}">Upload Devices</a><br>
    <a href="{% url 'poam:add-device' system.id %}">Add Device</a><br>
    <a href="{% url 'poam:select-device' system.id %}">Edit Devices</a><br>
    <a href="{% url 'poam:export-poam' system.id %}">Export POA&M</a><br>
    <a href="{% url 'poam:export-hw-sw-list' system.id %}">Export HW/SW List</a>

{% endblock %}

poam/templates/poam/new_poc.html
{% extends "base.html" %}

{% block title %}New System{% endblock %}

{% block content %}
    <h1>New Point of Contact</h1>
    {% if form.errors %}
        <p>There was an error creating your system</p>
    {% endif %}

    <div class="">
        <form action="{% url "poam:new-poc" %}" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Submit"></p>
        </form>
    </div>

{% endblock %}

poam/templates/poam/new_system.html
{% extends "base.html" %}

{% block title %}New System{% endblock %}

{% block content %}
    <h1>New System</h1>
    {% if form.errors %}
        <p>There was an error creating your system</p>
    {% endif %}

    <div class="">
        <form action="{% url "poam:new-system" %}" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><a href="{% url "poam:new-poc" %}">Create a new Point of Contact</a></p>
            <p><input type="submit" value="Submit"></p>
        </form>

    </div>

{% endblock %}

poam/templates/poam/select-device.html
{% extends "base.html" %}

{% block title %}Select System{% endblock %}

{% block content %}
    <h1>Select Device from {{ system.name }} System</h1>

    <form action="." method="post">
        {% csrf_token %}
        <select name="device" required>
            <option value=""selected disabled>Choose Device</option>
            {% for device in devices %}
                <option value="{{ device.id }}">{{ device.name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Go</button>
    </form>

{#	<!-- <a href="{% url "poam:upload-artifact" %}">Upload Artifacts</a><br>#}
{#	<a href="{% url 'poam:add-device' %}">Add Device</a> -->#}

{% endblock %}

poam/templates/poam/select-system.html
{% extends "base.html" %}

{% block title %}Select System{% endblock %}

{% block content %}
    <h1>Select System</h1>

	<form action="." method="post">
		{% csrf_token %}
		<select name="system" required>
			<option value=""selected disabled>Choose System</option>
			{% for system in systems %}
				<option value="{{ system.id }}">{{ system.name }}</option>
			{% endfor %}
		</select>
		<button type="submit">Go</button>
	</form>

{#	<!-- <a href="{% url "poam:upload-artifact" %}">Upload Artifacts</a><br>#}
{#	<a href="{% url 'poam:add-device' %}">Add Device</a> -->#}

{% endblock %}

poam/templates/poam/upload-poam.html
{% extends "base.html" %}

{% block title %}Upload POA&M{% endblock %}

{% block content %}
    <h1>Upload POA&M</h1>
    {% if form.errors %}
        <p>There was an error creating your system</p>
    {% endif %}

    <div>
        <h3>System: {{ system }}</h3>
         <form method="post" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit">Upload</button>
        </form><br>
         <a href="{% url 'poam:edit-system' system.id %}">Edit System</a>
    </div>

{% endblock %}

poam/templates/poam/upload_artifact.html
{% extends "base.html" %}

{% block title %}Upload Artifact{% endblock %}

{% block content %}
    <h1>Upload Artifact</h1>
    {% if form.errors %}
        <p>There was an error creating your system</p>
    {% endif %}

    <div class="">
         <form method="post" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit">Upload</button>
         </form>
         <br><br>
         <a href="{% url 'poam:add-device' system.id %}">Device not listed?</a><br>
         <a href="{% url 'poam:edit-system' system.id %}">Edit System</a>
    </div>

{% endblock %}

poam/templates/poam/upload_device.html
{% extends "base.html" %}

{% block title %}Upload Devices{% endblock %}

{% block content %}
    <h1>Upload Devices</h1>
    {% if form.errors %}
        <p>There was an error creating your system</p>
    {% endif %}

    <div>
        <h3>System: {{ system }}</h3>
         <form method="post" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit">Upload</button>
        </form><br>
         <a href="{% url 'poam:edit-system' system.id %}">Edit System</a>
    </div>

{% endblock %}